source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'ChouTi_Framework' do

  pod 'ChouTi', :path => '../'

end

target 'ChouTi_FrameworkTests' do

  pod 'ChouTi', :path => '../'

end
