# ChouTi document generator jazzy settings

copyright: Copyright © 2019 ChouTi.
author: HongHao Zhang
author_url: https://honghaoz.com
xcodebuild_arguments: [-target, ChouTi_iOS]
clean: true
output: ./Documentation
