name: ChouTi
options:
  bundleIdPrefix: com.chouti
  usesTabs: false
  indentWidth: 2
targets:
  ChouTi:
    type: framework
    platform: [iOS, tvOS]
    deploymentTarget:
      iOS: 12.0
      tvOS: 12.0
    sources: Sources
    info:
      path: Sources/Info.plist
    scheme:
      testTargets:
        - ChouTiTest_${platform}
      gatherCoverageData: true
  ChouTiTest:
    type: bundle.unit-test
    platform: [iOS, tvOS]
    sources: Tests
    info:
      path: Tests/Info.plist
    dependencies:
      - target: ChouTi_${platform}
      - carthage: Quick
      - carthage: Nimble
    settings:
      TEST_TARGET_NAME: ChouTi

# References:
#  - https://github.com/num42/RxUserDefaults/blob/master/project.yml
