source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'iOS-Example' do

pod 'ChouTi', :path => '../'
# pod 'ChouTi', :git => 'https://github.com/honghaoz/ChouTi'
# pod 'ChouTi/Unsafe'
# pod 'ChouTi/Unsafe', :path => '../'
# pod 'ChouTi/Safe', :path => '../'

pod 'ChouTi/Parse', :path => '../'

end
