platform :ios, '9.0'

target 'ChouTi iOS Example' do
  use_frameworks!

  # pod 'ChouTi', :git => 'https://github.com/honghaoz/ChouTi'

  pod 'ChouTi', :path => '../../'
  pod 'ChouTi/Utilities-Extra', :path => '../../'
  pod 'ChouTi/UI-Extra', :path => '../../'
  pod 'ChouTi/UI-App-Extension-API-Unsafe', :path => '../../'

  pod 'Then', '~> 1.0'

  target 'ChouTi iOS ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
