platform :ios, '8.0'

target 'ChouTi iOS Example' do
  use_frameworks!

#  pod 'ChouTi', :git => 'https://github.com/honghaoz/ChouTi'
#  pod 'ChouTi/ChouTi-Extra', :git => 'https://github.com/honghaoz/ChouTi'

   pod 'ChouTi', :path => '../../'
   pod 'ChouTi/ChouTi-Extra', :path => '../../'

  # pod 'ChouTi/Unsafe', :path => '../../'
  # pod 'ChouTi/Safe', :path => '../../'
  # pod 'ChouTi/Parse', :path => '../../'
  # pod 'ChouTi/UI/AutoLinesLabel', :path => '../../'

  pod 'Then', '~> 1.0'

  target 'ChouTi iOS ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
