platform :ios, '9.0'
use_frameworks!

# Pods
def pod_testing
  pod 'Quick', '~> 1.1'
  pod 'Nimble', '~> 6.1'
end

# Targets
target 'ChouTi iOS Tests' do
  pod_testing
end

target 'ChouTi Example iOS UITests' do
  pod_testing
end
