platform :ios, '9.0'
use_frameworks!

# Pods
def pod_testing
  pod 'Quick', '1.0'
  pod 'Nimble', '~> 5.1'
end

# Targets
target 'ChouTi' do

  target 'ChouTiTests' do
    inherit! :search_paths
    pod_testing
  end

end

target 'ChouTi iOS' do

  target 'ChouTi iOSUITests' do
    inherit! :search_paths
    pod_testing
  end

end
