fastlane_version "2.89.0"

default_platform :ios

platform :ios do

  desc "Release a new version of ChouTi"
  lane :release do |options|
    # Ensure Git status is clean
    ensure_git_status_clean
    # Ensure Git branch is master
    ensure_git_branch(branch: 'master')
    # Perform Tests
    tests
    # Retrieve Version from options
    version = options[:version]
    # Increment Version
    increment(version: version)
    # Add Git Tag
    add_git_tag(tag: version)
    # Push Git Tag
    push_git_tags()
    # Push Git commit
    push_to_git_remote()
    # Pod push / Pod trunk
    pod_push()
  end

  desc "Increment Version"
  lane :increment do |options|
    # Retrieve Version from options
    version = options[:version]
    # Set Podspec version
    version_bump_podspec(
      path: "ChouTi.podspec", 
      version_number: version
    )
    # Set Framework plist version
    set_info_plist_value(
      path: "Configs/ChouTi.plist", 
      key: "CFBundleShortVersionString", 
      value: version
    )
    # Set Framework Tests plist version
    set_info_plist_value(
      path: "Configs/ChouTiTests.plist", 
      key: "CFBundleShortVersionString", 
      value: version
    )
    # Set Example plist version
    set_info_plist_value(
      path: "Example/Resources/Info.plist", 
      key: "CFBundleShortVersionString", 
      value: version
    )
    # Commit modified files
    git_commit(
        path: [
          "ChouTi.podspec", 
          "Configs/ChouTi.plist", 
          "Configs/ChouTiTests.plist", 
          "Example/Resources/Info.plist"
        ],
        message: "ChouTi Version #{version} 🚀"
    )
  end

  desc "Runs Tests"
  lane :tests do
    # Carthage build to ensure Carthage compatibility
    carthage(
      command: "build", 
      no_skip_current: true, 
      cache_builds: true
    )
    # Pod lib lint to ensure CocoaPods compatibility
    pod_lib_lint
    # Perform iOS Tests
    scan(
      project: "ChouTi.xcodeproj",
      scheme: "ChouTi-iOS",
      clean: true
    )
  end

end
