name: build

on: [push]

jobs:
  iOS:
    name: iOS
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["OS=13.1,name=iPhone 11 Pro"]
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: make bootstrap
    - name: Build for debug on iOS - ${{ matrix.destination }}
      run: |
        set -o pipefail
        bundle exec rake xcode no_open=true
        bundle exec rake build
    - name: Upload Code Coverage
      run: bash <(curl -s https://codecov.io/bash) -J '^ChouTi$' -t ${{ secrets.CODECOV_TOKEN }}
    - name: Build for release on iOS - ${{ matrix.destination }}
      run: bundle exec rake build_release
